/**
 * Descrições dos códigos CID-10 mais comuns em atestados médicos.
 * Cobre os diagnósticos mais frequentes no contexto de saúde ocupacional brasileira.
 */
export const CID_DESCRICOES: Record<string, string> = {
  // ── A – Infecciosas e parasitárias ────────────────────────────────────────────
  A00: 'Cólera',
  A01: 'Febres tifóide e paratifóide',
  A02: 'Outras infecções por salmonelas',
  A03: 'Shiguelose',
  A04: 'Outras infecções intestinais bacterianas',
  A05: 'Outras intoxicações alimentares de origem bacteriana',
  A06: 'Amebíase',
  A07: 'Outras doenças intestinais por protozoários',
  A08: 'Infecções intestinais virais',
  A09: 'Diarreia e gastroenterite de origem infecciosa',
  A15: 'Tuberculose respiratória, confirmada bacteriologicamente',
  A16: 'Tuberculose das vias respiratórias, sem confirmação bacteriológica',
  A17: 'Tuberculose do sistema nervoso',
  A18: 'Tuberculose de outros órgãos',
  A19: 'Tuberculose miliar',
  A20: 'Peste',
  A22: 'Carbúnculo',
  A27: 'Leptospirose',
  A33: 'Tétano neonatal',
  A34: 'Tétano obstétrico',
  A35: 'Outros tipos de tétano',
  A36: 'Difteria',
  A37: 'Coqueluche',
  A38: 'Escarlatina',
  A39: 'Infecção meningocócica',
  A40: 'Septicemia estreptocócica',
  A41: 'Outras septicemias',
  A46: 'Erisipela',
  A49: 'Infecção bacteriana de localização não especificada',
  A50: 'Sífilis congênita',
  A51: 'Sífilis precoce',
  A52: 'Sífilis tardia',
  A53: 'Outras formas e sífilis não especificada',
  A54: 'Infecção gonocócica',
  A59: 'Tricomoníase',
  A60: 'Infecção anogenital pelo vírus do herpes (herpes simples)',
  A63: 'Outras doenças de transmissão predominantemente sexual',
  A77: 'Febre maculosa (riquetsioses transmitidas por carrapatos)',
  A90: 'Dengue',
  A91: 'Febre hemorrágica devida ao vírus do dengue',
  A98: 'Outras febres hemorrágicas virais',
  B00: 'Infecções pelo vírus do herpes simples',
  B01: 'Varicela (catapora)',
  B02: 'Herpes zóster',
  B05: 'Sarampo',
  B06: 'Rubéola',
  B07: 'Verrugas virais',
  B08: 'Outras infecções virais com lesões cutâneas e de mucosas',
  B15: 'Hepatite aguda A',
  B16: 'Hepatite aguda B',
  B17: 'Outras hepatites virais agudas',
  B18: 'Hepatite viral crônica',
  B19: 'Hepatite viral não especificada',
  B20: 'Doença pelo HIV resultando em doenças infecciosas e parasitárias',
  B24: 'Doença pelo HIV não especificada',
  B34: 'Infecção viral de localização não especificada',
  B35: 'Dermatofitose (tinea, micose superficial)',
  B36: 'Outras micoses superficiais',
  B37: 'Candidíase',
  B45: 'Criptococose',
  B49: 'Micose não especificada',
  B54: 'Malária não especificada',
  B82: 'Parasitose intestinal não especificada',
  B85: 'Pediculose e ftiriíase',
  B86: 'Escabiose (sarna)',
  B97: 'Agentes virais como causa de doenças classificadas em outros capítulos',
  // ── C – Neoplasias malignas ───────────────────────────────────────────────────
  C00: 'Neoplasia maligna do lábio',
  C16: 'Neoplasia maligna do estômago',
  C18: 'Neoplasia maligna do cólon',
  C20: 'Neoplasia maligna do reto',
  C22: 'Neoplasia maligna do fígado e dos ductos biliares intra-hepáticos',
  C25: 'Neoplasia maligna do pâncreas',
  C34: 'Neoplasia maligna dos brônquios e dos pulmões',
  C43: 'Melanoma maligno da pele',
  C50: 'Neoplasia maligna da mama',
  C53: 'Neoplasia maligna do colo do útero',
  C54: 'Neoplasia maligna do corpo do útero',
  C56: 'Neoplasia maligna do ovário',
  C61: 'Neoplasia maligna da próstata',
  C67: 'Neoplasia maligna da bexiga',
  C73: 'Neoplasia maligna da tireoide',
  C91: 'Leucemia linfoide',
  C92: 'Leucemia mieloide',
  // ── D – Benignos e sangue ─────────────────────────────────────────────────────
  D25: 'Leiomioma do útero (mioma)',
  D50: 'Anemia por deficiência de ferro',
  D51: 'Anemia por deficiência de vitamina B12',
  D52: 'Anemia por deficiência de folato',
  D64: 'Outras anemias',
  D69: 'Púrpura e outras afecções hemorrágicas',
  D70: 'Agranulocitose',
  D86: 'Sarcoidose',
  // ── E – Endócrinas e metabólicas ─────────────────────────────────────────────
  E00: 'Síndrome de deficiência congênita de iodo',
  E01: 'Transtornos da tireoide relacionados com deficiência de iodo',
  E03: 'Outros hipotireoidismos',
  E04: 'Bócio não tóxico',
  E05: 'Tireotoxicose (hipertireoidismo)',
  E06: 'Tireoidite',
  E10: 'Diabetes mellitus insulino-dependente (tipo 1)',
  E11: 'Diabetes mellitus não insulino-dependente (tipo 2)',
  E12: 'Diabetes mellitus associado à desnutrição',
  E13: 'Outros tipos especificados de diabetes mellitus',
  E14: 'Diabetes mellitus não especificado',
  E16: 'Outros transtornos da secreção pancreática interna',
  E27: 'Outros transtornos da glândula suprarrenal',
  E28: 'Disfunção ovariana',
  E29: 'Disfunção testicular',
  E34: 'Outros transtornos endócrinos',
  E40: 'Kwashiorkor',
  E41: 'Marasmo nutricional',
  E44: 'Desnutrição proteico-calórica de grau moderado e discreto',
  E50: 'Deficiência de vitamina A',
  E55: 'Deficiência de vitamina D',
  E58: 'Deficiência alimentar de cálcio',
  E61: 'Deficiência de outros elementos nutricionais',
  E63: 'Outras deficiências nutricionais',
  E65: 'Adiposidade localizada',
  E66: 'Obesidade',
  E78: 'Distúrbios do metabolismo de lipoproteínas e outras lipidemias',
  E79: 'Distúrbios do metabolismo da purina e pirimidina',
  E83: 'Distúrbios do metabolismo mineral',
  E86: 'Depleção de volume (desidratação)',
  E87: 'Outros distúrbios do equilíbrio hidroeletrolítico e ácido-base',
  // ── F – Transtornos mentais e comportamentais ─────────────────────────────────
  F00: 'Demência na doença de Alzheimer',
  F01: 'Demência vascular',
  F02: 'Demência em outras doenças classificadas em outra parte',
  F03: 'Demência não especificada',
  F04: 'Síndrome amnésica orgânica não induzida por álcool ou outras substâncias',
  F05: 'Delirium não induzido por álcool ou outras substâncias psicoativas',
  F06: 'Outros transtornos mentais devidos a lesão e disfunção cerebral',
  F07: 'Transtornos de personalidade e de comportamento devidos a doença, lesão ou disfunção cerebral',
  F09: 'Transtorno mental orgânico ou sintomático não especificado',
  F10: 'Transtornos mentais e comportamentais devidos ao uso de álcool',
  F11: 'Transtornos mentais e comportamentais devidos ao uso de opioides',
  F12: 'Transtornos mentais e comportamentais devidos ao uso de canabinoides',
  F13: 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos',
  F14: 'Transtornos mentais e comportamentais devidos ao uso de cocaína',
  F15: 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes',
  F17: 'Transtornos mentais e comportamentais devidos ao uso de fumo (tabaco)',
  F19: 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas',
  F20: 'Esquizofrenia',
  F21: 'Transtorno esquizotípico',
  F22: 'Transtornos delirantes persistentes',
  F25: 'Transtornos esquizoafetivos',
  F28: 'Outros transtornos psicóticos não orgânicos',
  F29: 'Psicose não orgânica não especificada',
  F30: 'Episódio maníaco',
  F31: 'Transtorno afetivo bipolar',
  F32: 'Episódios depressivos',
  F33: 'Transtorno depressivo recorrente',
  F34: 'Transtornos de humor (afetivos) persistentes',
  F38: 'Outros transtornos do humor (afetivos)',
  F39: 'Transtorno do humor (afetivo) não especificado',
  F40: 'Transtornos fóbico-ansiosos',
  F41: 'Outros transtornos ansiosos',
  F42: 'Transtorno obsessivo-compulsivo',
  F43: 'Reações ao stress grave e transtornos de adaptação',
  F44: 'Transtornos dissociativos (de conversão)',
  F45: 'Transtornos somatoformes',
  F48: 'Outros transtornos neuróticos',
  F50: 'Transtornos da alimentação (anorexia, bulimia)',
  F51: 'Transtornos do sono não orgânicos',
  F54: 'Fatores psicológicos e comportamentais associados a doenças ou transtornos',
  F60: 'Transtornos específicos da personalidade',
  F63: 'Transtornos dos hábitos e impulsos',
  F70: 'Retardo mental leve',
  F71: 'Retardo mental moderado',
  F80: 'Transtornos específicos do desenvolvimento da fala e da linguagem',
  F84: 'Transtornos globais do desenvolvimento (autismo)',
  F90: 'Transtornos hipercinéticos (TDAH)',
  F91: 'Transtornos de conduta',
  F95: 'Tiques',
  F99: 'Transtorno mental não especificado',
  // ── G – Sistema nervoso ───────────────────────────────────────────────────────
  G00: 'Meningite bacteriana',
  G02: 'Meningite em doenças virais',
  G03: 'Meningite devida a outras causas e a causas não especificadas',
  G04: 'Encefalite, mielite e encefalomielite',
  G06: 'Abscesso e granuloma intracranianos e intraespinhais',
  G20: 'Doença de Parkinson',
  G30: 'Doença de Alzheimer',
  G35: 'Esclerose múltipla',
  G40: 'Epilepsia',
  G41: 'Estado de mal epiléptico',
  G43: 'Enxaqueca (migrânea)',
  G44: 'Outras síndromes de algias cefálicas (cefaleia tensional e outras)',
  G45: 'Ataques isquêmicos transitórios',
  G47: 'Transtornos do sono',
  G50: 'Transtornos do nervo trigêmeo',
  G51: 'Transtornos do nervo facial',
  G54: 'Transtornos das raízes e dos plexos nervosos',
  G56: 'Mononeuropatias do membro superior (síndrome do túnel do carpo)',
  G57: 'Mononeuropatias do membro inferior',
  G58: 'Outras mononeuropatias',
  G61: 'Polineuropatia inflamatória',
  G62: 'Outras polineuropatias',
  G63: 'Polineuropatia em doenças classificadas em outra parte',
  G80: 'Paralisia cerebral',
  G89: 'Outros transtornos do sistema nervoso',
  G93: 'Outros transtornos do encéfalo',
  G99: 'Outros transtornos do sistema nervoso em doenças classificadas em outra parte',
  // ── H00-H59 – Olho e anexos ───────────────────────────────────────────────────
  H00: 'Hordéolo e calázio',
  H01: 'Outras inflamações da pálpebra',
  H10: 'Conjuntivite',
  H11: 'Outros transtornos da conjuntiva',
  H16: 'Ceratite',
  H20: 'Iridociclite',
  H25: 'Catarata senil',
  H26: 'Outras cataratas',
  H33: 'Descolamento e defeitos da retina',
  H35: 'Outros transtornos da retina',
  H40: 'Glaucoma',
  H43: 'Transtornos do corpo vítreo',
  H52: 'Transtornos da acomodação e da refração',
  H53: 'Distúrbios visuais',
  H54: 'Cegueira e visão subnormal',
  // ── H60-H95 – Ouvido ──────────────────────────────────────────────────────────
  H60: 'Otite externa',
  H61: 'Outros transtornos do ouvido externo',
  H65: 'Otite média não supurativa',
  H66: 'Otite média supurativa e não especificada',
  H70: 'Mastoidite e afecções correlatas',
  H72: 'Perfuração da membrana do tímpano',
  H80: 'Otosclerose',
  H81: 'Transtornos da função vestibular (vertigem, labirintite)',
  H83: 'Outros transtornos do ouvido interno',
  H90: 'Perda de audição por transtorno de condução e neuro-sensorial',
  H91: 'Outras perdas de audição',
  H92: 'Otalgia e otorreia',
  // ── I – Aparelho circulatório ─────────────────────────────────────────────────
  I05: 'Doenças reumáticas da valva mitral',
  I08: 'Doenças de múltiplas valvas',
  I09: 'Outras doenças reumáticas do coração',
  I10: 'Hipertensão essencial (primária)',
  I11: 'Doença cardíaca hipertensiva',
  I12: 'Doença renal hipertensiva',
  I13: 'Doença cardíaca e renal hipertensiva',
  I15: 'Hipertensão secundária',
  I20: 'Angina pectoris',
  I21: 'Infarto agudo do miocárdio',
  I22: 'Infarto do miocárdio recorrente',
  I25: 'Doença isquêmica crônica do coração',
  I26: 'Embolia pulmonar',
  I27: 'Outras formas de doença cardíaca pulmonar',
  I30: 'Pericardite aguda',
  I34: 'Transtornos não reumáticos da valva mitral',
  I42: 'Cardiomiopatia',
  I44: 'Bloqueio atrioventricular e de ramo esquerdo',
  I47: 'Taquicardia paroxística',
  I48: 'Fibrilação e flutter atrial',
  I49: 'Outras arritmias cardíacas',
  I50: 'Insuficiência cardíaca',
  I51: 'Complicações e doenças cardíacas mal definidas',
  I60: 'Hemorragia subaracnoidea',
  I61: 'Hemorragia intracerebral',
  I63: 'Infarto cerebral',
  I64: 'Acidente vascular cerebral (AVC), não especificado',
  I67: 'Outras doenças cerebrovasculares',
  I69: 'Sequelas de doenças cerebrovasculares',
  I73: 'Outras doenças vasculares periféricas',
  I74: 'Embolia e trombose arteriais',
  I80: 'Flebite e tromboflebite',
  I83: 'Varizes dos membros inferiores',
  I84: 'Hemorroidas',
  I87: 'Outros transtornos das veias',
  I89: 'Outros transtornos não infecciosos dos vasos e dos linfonodos linfáticos',
  I95: 'Hipotensão',
  // ── J – Aparelho respiratório ─────────────────────────────────────────────────
  J00: 'Nasofaringite aguda (resfriado comum)',
  J01: 'Sinusite aguda',
  J02: 'Faringite aguda',
  J03: 'Amigdalite aguda',
  J04: 'Laringite e traqueíte agudas',
  J05: 'Laringite obstrutiva aguda (crupe) e epiglotite',
  J06: 'Infecções agudas das vias aéreas superiores de localizações múltiplas e não especificadas',
  J10: 'Influenza devida a vírus influenza identificado',
  J11: 'Influenza devida a vírus não identificado',
  J12: 'Pneumonia viral',
  J13: 'Pneumonia por Streptococcus pneumoniae',
  J14: 'Pneumonia por Haemophilus influenzae',
  J15: 'Pneumonia bacteriana',
  J16: 'Pneumonia devida a outros microorganismos infecciosos',
  J18: 'Pneumonia por microorganismo não especificado',
  J20: 'Bronquite aguda',
  J21: 'Bronquiolite aguda',
  J22: 'Infecção aguda não especificada das vias aéreas inferiores',
  J30: 'Rinite vasomotora e alérgica',
  J31: 'Rinite crônica, nasofaringite e faringoamigdalite',
  J32: 'Sinusite crônica',
  J33: 'Pólipo nasal',
  J34: 'Outros transtornos do nariz e dos seios paranasais',
  J35: 'Doenças crônicas das amígdalas e das adenoides',
  J37: 'Laringite e laringotraqueíte crônicas',
  J38: 'Doenças das pregas vocais e da laringe',
  J39: 'Outras doenças das vias aéreas superiores',
  J40: 'Bronquite não especificada como aguda ou crônica',
  J41: 'Bronquite crônica simples e mucopurulenta',
  J42: 'Bronquite crônica não especificada',
  J43: 'Enfisema',
  J44: 'Outras doenças pulmonares obstrutivas crônicas (DPOC)',
  J45: 'Asma',
  J46: 'Estado de mal asmático',
  J47: 'Bronquiectasia',
  J60: 'Pneumoconiose dos mineiros de carvão',
  J68: 'Afecções respiratórias devidas à inalação de substâncias químicas',
  J69: 'Pneumonite devida a sólidos e líquidos',
  J80: 'Síndrome do desconforto respiratório do adulto',
  J82: 'Eosinofilia pulmonar',
  J84: 'Outras doenças pulmonares intersticiais',
  J90: 'Derrame pleural',
  J93: 'Pneumotórax',
  J96: 'Insuficiência respiratória',
  J98: 'Outros transtornos respiratórios',
  // ── K – Aparelho digestivo ────────────────────────────────────────────────────
  K00: 'Transtornos do desenvolvimento e da erupção dos dentes',
  K02: 'Cárie dentária',
  K04: 'Doenças da polpa e dos tecidos periapicais',
  K05: 'Gengivite e doença periodontal',
  K08: 'Outros transtornos dos dentes e das estruturas de suporte',
  K11: 'Doenças das glândulas salivares',
  K12: 'Estomatite e afecções correlatas',
  K20: 'Esofagite',
  K21: 'Doença de refluxo gastroesofágico (DRGE)',
  K22: 'Outras doenças do esôfago',
  K25: 'Úlcera gástrica',
  K26: 'Úlcera duodenal',
  K27: 'Úlcera péptica de localização não especificada',
  K29: 'Gastrite e duodenite',
  K30: 'Dispepsia',
  K31: 'Outras doenças do estômago e do duodeno',
  K35: 'Apendicite aguda',
  K36: 'Outras formas de apendicite',
  K40: 'Hérnia inguinal',
  K41: 'Hérnia femoral',
  K42: 'Hérnia umbilical',
  K43: 'Hérnia ventral',
  K44: 'Hérnia diafragmática',
  K50: 'Doença de Crohn',
  K51: 'Colite ulcerativa',
  K52: 'Outras colites e gastroenterites não infecciosas',
  K56: 'Íleo paralítico e obstrução intestinal',
  K57: 'Doença diverticular do intestino',
  K58: 'Síndrome do intestino irritável',
  K59: 'Outros transtornos funcionais do intestino',
  K60: 'Fissura e fístula das regiões anal e retal',
  K61: 'Abscesso das regiões anal e retal',
  K62: 'Outras doenças do reto e do ânus',
  K63: 'Outras doenças do intestino',
  K70: 'Doença alcoólica do fígado',
  K72: 'Insuficiência hepática',
  K73: 'Hepatite crônica',
  K74: 'Fibrose e cirrose hepática',
  K76: 'Outras doenças do fígado',
  K80: 'Colelitíase (cálculo biliar)',
  K81: 'Colecistite',
  K82: 'Outras doenças da vesícula biliar',
  K83: 'Outras doenças das vias biliares',
  K85: 'Pancreatite aguda',
  K86: 'Outras doenças do pâncreas',
  K92: 'Outras doenças do aparelho digestivo',
  K93: 'Transtornos de outros órgãos digestivos em doenças classificadas em outra parte',
  // ── L – Pele e tecido subcutâneo ──────────────────────────────────────────────
  L00: 'Síndrome da pele escaldada estafilocócica',
  L01: 'Impetigo',
  L02: 'Abscesso cutâneo, furúnculo e antraz',
  L03: 'Celulite',
  L04: 'Linfadenite aguda',
  L08: 'Outras infecções localizadas da pele e do tecido subcutâneo',
  L10: 'Pênfigo',
  L13: 'Outros transtornos bolhosos',
  L20: 'Dermatite atópica (eczema atópico)',
  L21: 'Dermatite seborreica',
  L22: 'Dermatite das fraldas',
  L23: 'Dermatite de contato alérgica',
  L24: 'Dermatite de contato por irritante',
  L25: 'Dermatite de contato não especificada',
  L27: 'Dermatite devida a substâncias ingeridas',
  L28: 'Líquen simples crônico e prurigo',
  L29: 'Prurido',
  L30: 'Outras dermatites',
  L40: 'Psoríase',
  L41: 'Parapsoríase',
  L42: 'Pitiríase rósea',
  L43: 'Líquen plano',
  L50: 'Urticária',
  L51: 'Eritema multiforme',
  L57: 'Alterações da pele devidas à exposição crônica à radiação não ionizante',
  L60: 'Transtornos das unhas',
  L70: 'Acne',
  L71: 'Rosácea',
  L72: 'Cistos foliculares da pele e do tecido subcutâneo',
  L73: 'Outras doenças dos folículos pilosos',
  L80: 'Vitiligo',
  L81: 'Outros transtornos da pigmentação',
  L84: 'Calos e calosidades',
  L89: 'Úlcera de decúbito (escare)',
  L90: 'Transtornos atróficos da pele',
  L92: 'Transtornos granulomatosos da pele e do tecido subcutâneo',
  L97: 'Úlcera do membro inferior',
  L98: 'Outras doenças da pele e do tecido subcutâneo',
  // ── M – Sistema osteomuscular ─────────────────────────────────────────────────
  M00: 'Artrite piogênica',
  M01: 'Infecções diretas da articulação em doenças infecciosas e parasitárias',
  M05: 'Artrite reumatoide soropositiva',
  M06: 'Outras artrites reumatoides',
  M08: 'Artrite juvenil',
  M10: 'Gota',
  M13: 'Outras artrites',
  M15: 'Poliartrose',
  M16: 'Coxartrose (artrose do quadril)',
  M17: 'Gonartrose (artrose do joelho)',
  M18: 'Artrose da primeira articulação carpometacarpiana',
  M19: 'Outras artroses',
  M20: 'Deformidades adquiridas dos dedos das mãos e dos pés',
  M23: 'Transtornos internos do joelho',
  M24: 'Outros transtornos articulares específicos',
  M25: 'Outros transtornos articulares',
  M32: 'Lúpus eritematoso sistêmico',
  M33: 'Dermatomiosite/poliomiosite',
  M34: 'Esclerose sistêmica (escleroderma)',
  M35: 'Outras afecções sistêmicas do tecido conjuntivo',
  M40: 'Cifose e lordose',
  M41: 'Escoliose',
  M42: 'Osteocondrose da coluna vertebral',
  M43: 'Outras dorsopatias deformantes',
  M45: 'Espondilite anquilosante',
  M46: 'Outras espondilopatias inflamatórias',
  M47: 'Espondilose (espondilartrose)',
  M48: 'Outras espondilopatias',
  M50: 'Transtornos dos discos cervicais',
  M51: 'Outros transtornos dos discos intervertebrais',
  M53: 'Outras dorsopatias',
  M54: 'Dorsalgia (lombalgia, cervicalgia, ciatalgia)',
  M60: 'Miosite',
  M61: 'Calcificação e ossificação muscular',
  M62: 'Outros transtornos musculares',
  M65: 'Sinovite e tenossinovite',
  M66: 'Ruptura espontânea da sinóvia e do tendão',
  M67: 'Outros transtornos da sinóvia e do tendão',
  M70: 'Transtornos dos tecidos moles relacionados com o uso, o uso excessivo e a pressão',
  M71: 'Outras bursopatias',
  M72: 'Transtornos fibroblásticos',
  M75: 'Lesões do ombro (tendinite, bursite, síndrome do manguito rotador)',
  M76: 'Entesopatias do membro inferior',
  M77: 'Outras entesopatias (epicondilite, fascite plantar)',
  M79: 'Outros transtornos dos tecidos moles não classificados em outra parte (fibromialgia)',
  M80: 'Osteoporose com fratura patológica',
  M81: 'Osteoporose sem fratura patológica',
  M85: 'Outros transtornos da densidade e da estrutura óssea',
  M86: 'Osteomielite',
  M87: 'Osteonecrose',
  M94: 'Outros transtornos das cartilagens',
  M99: 'Lesões biomecânicas não classificadas em outra parte',
  // ── N – Aparelho geniturinário ────────────────────────────────────────────────
  N00: 'Síndrome nefrítica aguda',
  N03: 'Síndrome nefrítica crônica',
  N04: 'Síndrome nefrótica',
  N10: 'Nefrite tubulointersticial aguda (pielonefrite aguda)',
  N11: 'Nefrite tubulointersticial crônica',
  N17: 'Insuficiência renal aguda',
  N18: 'Insuficiência renal crônica',
  N20: 'Calculose do rim e do ureter (cálculo renal)',
  N21: 'Calculose do trato urinário inferior',
  N23: 'Cólica renal não especificada',
  N28: 'Outros transtornos do rim e do ureter',
  N30: 'Cistite',
  N34: 'Uretrite e síndrome uretral',
  N35: 'Estenose da uretra',
  N39: 'Outros transtornos do aparelho urinário (infecção urinária)',
  N40: 'Hiperplasia da próstata',
  N41: 'Doenças inflamatórias da próstata (prostatite)',
  N42: 'Outros transtornos da próstata',
  N45: 'Orquite e epididimite',
  N48: 'Outros transtornos do pênis',
  N60: 'Displasia mamária',
  N70: 'Salpingite e ooforite',
  N71: 'Doença inflamatória do útero',
  N72: 'Doença inflamatória do colo do útero (cervicite)',
  N73: 'Outras doenças inflamatórias pélvicas femininas',
  N76: 'Outras infecções vaginais e vulvares',
  N80: 'Endometriose',
  N83: 'Transtornos não inflamatórios do ovário, da tuba uterina e do ligamento largo',
  N87: 'Displasia cervical',
  N89: 'Outros transtornos não inflamatórios da vagina',
  N90: 'Outros transtornos não inflamatórios da vulva e do períneo',
  N91: 'Menstruação ausente, escassa e rara (amenorreia)',
  N92: 'Menstruação excessiva, frequente e irregular',
  N93: 'Outras hemorragias uterinas ou vaginais anormais',
  N94: 'Dor e outras afecções associadas aos órgãos genitais femininos e ao ciclo menstrual',
  N95: 'Transtornos da menopausa e do climatério feminino',
  N99: 'Outros transtornos do aparelho geniturinário',
  // ── O – Gravidez, parto e puerpério ──────────────────────────────────────────
  O00: 'Gravidez ectópica',
  O03: 'Aborto espontâneo',
  O09: 'Duração da gravidez',
  O10: 'Hipertensão pré-existente complicando a gravidez',
  O11: 'Distúrbios hipertensivos pré-existentes com proteinúria superajuntada',
  O12: 'Edema e proteinúria gestacionais',
  O13: 'Hipertensão gestacional (induzida pela gravidez)',
  O14: 'Pré-eclampsia',
  O15: 'Eclampsia',
  O20: 'Hemorragia no início da gravidez',
  O21: 'Vômitos excessivos na gravidez (hiperêmese gravídica)',
  O24: 'Diabetes mellitus na gravidez',
  O26: 'Cuidados à mãe por outras condições predominantemente relacionadas com a gravidez',
  O28: 'Achados anormais no exame pré-natal materno',
  O30: 'Gestação múltipla',
  O34: 'Cuidados maternos por anormalidades conhecidas ou suspeitas dos órgãos pélvicos maternos',
  O42: 'Ruptura prematura de membranas',
  O48: 'Gravidez prolongada',
  O60: 'Trabalho de parto prematuro',
  O80: 'Parto único espontâneo',
  O82: 'Parto por cesariana',
  O85: 'Sepse puerperal',
  O90: 'Complicações do puerpério',
  // ── P – Período perinatal ─────────────────────────────────────────────────────
  P07: 'Transtornos relacionados com a gestação curta e baixo peso ao nascer',
  P22: 'Desconforto respiratório do recém-nascido',
  P36: 'Septicemia bacteriana do recém-nascido',
  P59: 'Icterícia neonatal devida a outras causas e a causas não especificadas',
  // ── Q – Malformações congênitas ───────────────────────────────────────────────
  Q21: 'Malformações congênitas das câmaras cardíacas e das comunicações',
  Q35: 'Fenda palatina',
  Q36: 'Lábio leporino',
  Q65: 'Deformidades congênitas do quadril',
  Q66: 'Deformidades congênitas dos pés',
  Q90: 'Síndrome de Down (trissomia do cromossomo 21)',
  // ── R – Sintomas e sinais ─────────────────────────────────────────────────────
  R00: 'Anormalidades do batimento cardíaco',
  R04: 'Hemorragia das vias respiratórias',
  R05: 'Tosse',
  R06: 'Anormalidades da respiração',
  R07: 'Dor de garganta e no peito',
  R09: 'Outros sintomas e sinais relativos aos aparelhos circulatório e respiratório',
  R10: 'Dor abdominal e pélvica',
  R11: 'Náusea e vômito',
  R12: 'Pirose (azia)',
  R13: 'Disfagia',
  R14: 'Flatulência e afecções correlatas',
  R15: 'Incontinência fecal',
  R17: 'Icterícia não especificada',
  R18: 'Ascite',
  R19: 'Outros sintomas e sinais relativos ao aparelho digestivo e ao abdome',
  R20: 'Perturbações da sensibilidade cutânea',
  R21: 'Erupção e outras afecções não especificadas da pele',
  R25: 'Movimentos involuntários anormais',
  R26: 'Anormalidades da marcha e da mobilidade',
  R29: 'Outros sintomas e sinais relativos aos sistemas nervoso e musculoesquelético',
  R30: 'Dor associada à micção',
  R31: 'Hematúria não especificada',
  R32: 'Incontinência urinária não especificada',
  R33: 'Retenção de urina',
  R35: 'Poliúria',
  R39: 'Outros sintomas e sinais relativos ao aparelho urinário',
  R41: 'Outros sintomas e sinais relativos às funções cognitivas e à consciência',
  R42: 'Tontura e instabilidade',
  R43: 'Perturbações do olfato e do paladar',
  R45: 'Sintomas e sinais relativos ao estado emocional',
  R46: 'Sintomas e sinais relativos ao aspecto e ao comportamento',
  R47: 'Perturbações da fala',
  R49: 'Perturbações da voz',
  R50: 'Febre de origem desconhecida',
  R51: 'Cefaleia',
  R52: 'Dor não classificada em outra parte',
  R53: 'Mal-estar e fadiga',
  R54: 'Senilidade',
  R55: 'Síncope e colapso',
  R56: 'Convulsões',
  R57: 'Choque não classificado em outra parte',
  R58: 'Hemorragia não classificada em outra parte',
  R60: 'Edema não classificado em outra parte',
  R63: 'Sintomas e sinais relativos à ingestão de alimentos e líquidos',
  R65: 'Síndrome da resposta inflamatória sistêmica',
  R68: 'Outros sintomas e sinais gerais especificados',
  R73: 'Glicemia elevada',
  R74: 'Achados anormais de enzimas séricas',
  R75: 'Achados laboratoriais de vírus de imunodeficiência humana (HIV)',
  R83: 'Achados anormais no líquido cefalorraquidiano',
  R99: 'Outras causas mal definidas e não especificadas de mortalidade',
  // ── S – Lesões, traumatismos ───────────────────────────────────────────────────
  S00: 'Traumatismo superficial da cabeça',
  S01: 'Ferimento da cabeça',
  S02: 'Fratura do crânio e dos ossos da face',
  S06: 'Traumatismo intracraniano',
  S09: 'Outros traumatismos da cabeça e os não especificados',
  S10: 'Traumatismo superficial do pescoço',
  S12: 'Fratura do pescoço',
  S13: 'Luxação, entorse e distensão de articulações e ligamentos do pescoço',
  S19: 'Outros traumatismos do pescoço e os não especificados',
  S20: 'Traumatismo superficial do tórax',
  S22: 'Fratura de costela, do esterno e da coluna torácica',
  S27: 'Traumatismo de outros órgãos intratorácicos',
  S30: 'Traumatismo superficial do abdome, da região lombossacra e da pelve',
  S32: 'Fratura da coluna lombar e da pelve',
  S33: 'Luxação, entorse e distensão das articulações e dos ligamentos da coluna lombar e da pelve',
  S39: 'Outros traumatismos do abdome, da região lombossacra e da pelve',
  S40: 'Traumatismo superficial do ombro e do braço',
  S42: 'Fratura do ombro e do braço',
  S43: 'Luxação, entorse e distensão de articulações e ligamentos da cintura escapular',
  S46: 'Traumatismo de músculo e tendão ao nível do ombro e do braço',
  S50: 'Traumatismo superficial do antebraço',
  S52: 'Fratura do antebraço',
  S53: 'Luxação, entorse e distensão de articulações e ligamentos do cotovelo',
  S60: 'Traumatismo superficial do punho e da mão',
  S61: 'Ferimento do punho e da mão',
  S62: 'Fratura ao nível do punho e da mão',
  S63: 'Luxação, entorse e distensão de articulações e ligamentos do punho e da mão',
  S70: 'Traumatismo superficial do quadril e da coxa',
  S72: 'Fratura do fêmur',
  S73: 'Luxação, entorse e distensão da articulação e dos ligamentos do quadril',
  S80: 'Traumatismo superficial da perna',
  S82: 'Fratura da perna, incluindo o tornozelo',
  S83: 'Luxação, entorse e distensão de articulações e ligamentos do joelho',
  S90: 'Traumatismo superficial do tornozelo e do pé',
  S92: 'Fratura do pé',
  S93: 'Luxação, entorse e distensão de articulações e ligamentos do tornozelo e do pé',
  // ── T – Outras lesões e causas externas ──────────────────────────────────────
  T08: 'Fratura da coluna vertebral de nível não especificado',
  T14: 'Traumatismo de região não especificada do corpo',
  T20: 'Queimadura e corrosão da cabeça e do pescoço',
  T21: 'Queimadura e corrosão do tronco',
  T22: 'Queimadura e corrosão do ombro e do membro superior',
  T23: 'Queimadura e corrosão do punho e da mão',
  T24: 'Queimadura e corrosão do quadril e do membro inferior',
  T25: 'Queimadura e corrosão do tornozelo e do pé',
  T30: 'Queimadura e corrosão de região não especificada do corpo',
  T36: 'Intoxicação por antibióticos sistêmicos',
  T39: 'Intoxicação por analgésicos, antipiréticos e anti-reumáticos',
  T40: 'Intoxicação por narcóticos e psicodislépticos',
  T45: 'Intoxicação por agentes primariamente sistêmicos e hematológicos',
  T57: 'Efeitos tóxicos de outras substâncias inorgânicas',
  T65: 'Efeitos tóxicos de outras substâncias e as não especificadas',
  T78: 'Efeitos adversos não classificados em outra parte (choque anafilático, alergia)',
  T79: 'Algumas complicações precoces de traumatismos',
  T84: 'Complicações de dispositivos protéticos, implantes e enxertos internos ortopédicos',
  T88: 'Outros efeitos adversos de procedimentos cirúrgicos e médicos',
  T90: 'Sequelas de traumatismos da cabeça',
  T91: 'Sequelas de traumatismos do pescoço e do tronco',
  T92: 'Sequelas de traumatismos do membro superior',
  T93: 'Sequelas de traumatismos do membro inferior',
  T96: 'Sequelas de intoxicação por drogas, medicamentos e substâncias biológicas',
  // ── Z – Fatores que influenciam o estado de saúde ─────────────────────────────
  Z00: 'Exame geral e investigação de pessoas sem queixas',
  Z01: 'Outros exames e investigações de pessoas sem queixas',
  Z02: 'Exame e encontro para fins administrativos',
  Z03: 'Exame médico e observação por suspeita de doenças e condições',
  Z04: 'Exame e observação por outras razões',
  Z09: 'Exame de seguimento após tratamento por outras condições',
  Z10: 'Exame de saúde de rotina de subgrupos populacionais definidos',
  Z11: 'Exame de rastreamento especial para doenças infecciosas e parasitárias',
  Z12: 'Exame de rastreamento especial para neoplasias',
  Z13: 'Exame de rastreamento especial para outras doenças e transtornos',
  Z20: 'Contato com e exposição a doenças transmissíveis',
  Z23: 'Necessidade de imunização',
  Z30: 'Assistência para anticoncepção',
  Z34: 'Supervisão de gravidez normal',
  Z36: 'Rastreamento pré-natal',
  Z39: 'Cuidados e exames do pós-parto',
  Z41: 'Procedimentos para outros fins que não para tratar condição presente',
  Z47: 'Outros cuidados de acompanhamento após cirurgia ortopédica',
  Z48: 'Outros cuidados de acompanhamento cirúrgico',
  Z50: 'Cuidados que envolvem o uso de reabilitação',
  Z51: 'Outros cuidados médicos',
  Z54: 'Convalescença',
  Z57: 'Exposição ocupacional a fatores de risco',
  Z71: 'Pessoas que utilizam os serviços de saúde para outros fins',
  Z73: 'Problemas relacionados com a organização do modo de vida (esgotamento, burnout)',
  Z74: 'Problemas relacionados com a dependência em relação a prestadores de cuidados',
  Z75: 'Problemas relacionados com recursos de cuidados à saúde',
  Z76: 'Pessoas que utilizam os serviços de saúde em outras circunstâncias',
  Z82: 'História familiar de certas incapacidades e doenças crônicas',
  Z85: 'História pessoal de neoplasia maligna',
  Z87: 'História pessoal de outras doenças e condições',
  Z96: 'Presença de outros implantes funcionais',
  Z98: 'Outros estados pós-cirúrgicos',
}

/**
 * Retorna a descrição de um código CID-10.
 * Ignora subdivisões (ex: "J11.1" → busca "J11").
 */
export function getCidDescricao(cid: string): string | null {
  if (!cid) return null
  const base = cid.trim().toUpperCase().replace(/\..+$/, '')
  return CID_DESCRICOES[base] ?? null
}
